### ISSUE TITLE
koodikatselmointi

### ISSUE THREAD

**Issue by PetroLeh** [iosonja/ot-harjoitustyo#1]
(ladattu 28.4. klo 18.25.)

Hei!
Työsi aihe on mielenkiintoinen ja tutustun mielellään myös valmiiseen ohjelmaan, kun sen aika on. Aina mukava pelata peliä, josta samalla oppii jotain.

OIen itse vasta äskettäin alkanut opetella Pythonia ja piti asennella Poetry ja säätää hieman, mutta näiden omien alkusäätöjen jälkeen ohjelmasi toimi hienosti ja kirjoittamasi ohjeet sekä dokumentaatio ovat todella selkeät ja hyvät. Myös itse koodi on siistiä ja ymmärrettävää. Tuohon pitäisi pyrkiä, kun sain koodistasi ehkä paremmin selkoa kuin omastani. Luokkajako on looginen ja toteuttaa single responsibility -periaatteen.

Vaikea keksiä kovasti parannettavaa. Gameloop-moduulissa olit kommentoinut erään ehtolauseen lakanneen toimimasta. Tämä lienee kohta, josta Pylint antaa ainoan huomatuksen 'unnecessary elif after return'?

Voisiko ohjelman dynaamisuutta lisätä esimerkiksi vaihtelevalla nopeudella tai kuplien määrällä? Tämäkin kysymys on enemmän makuasia kuin laatuasia ja tulee tietysti muuttumaan työn edetessä.

Yhtä kaikki, laadukasta työtä!

**Comment by iosonja** [comment]
Kiitos palautteesta! Harmi että osuit juuri tähän kohtaan, kun käyttöohjeita ei ole vielä päivitetty eilisten isojen lähdekoodimuutosten jäljiltä. Pahoittelut siitä. Olen yrittänyt saada ohjelmaa printtaamaan oikean vastauksen terminaaliin aina uuden kuplan ilmaantuessa, jotta peliä voi pelata kuka tahansa, mutta jostain syystä refaktoroinnin jäljiltä kaikki nuo ohjaprinttaukset tulevat nyt vasta sen jälkeen kun ohjelma on lopetettu. Kiitos kun mainitsit pylintin elif-huomautuksesta, olen korjannut tuon tyylivirheen mutta näköjään unohtanut muutoksen stashed-tilaan!
